name: Build ZIP

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: chmod +x ./build.sh && ./build.sh

      - name: Upload ZIP
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./extension.zip
          tag: ${{ github.ref }}
          prerelease: true
          overwrite: true